### PR TITLE
[FIX] pep8

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by max3903** [comment]
Very good job here! Thanks for fixing the PEP8 errors.

Can you add the missing external dependency on mx.DateTime in paydays and fix the pylint errors ?

**Comment by eLBati** [comment]
Hello @max3903 , fixed!

**Comment by max3903** [comment]
Marvelous!
:+1:

**Comment by rvalyi** [comment]
:+1: thanks @eLBati and kudos for the amount of work!

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
