### PR TITLE
[IMP] multi-company domain rule

### PR DESCRIPTION
**Pull request by AntoniRomera**
Modified rule for standard outlined in migration guide v13

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Oh, please add migration script as stated in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#tasks-to-do-in-the-migration

**Comment by AntoniRomera** [comment]
But is a correction for a rule domain in v13, this is not a migration.

Multi-company record rules now need to have this general form: ['|',('company_id','=',False),('company_id','in',company_ids)]</field>

**Comment by pedrobaeza** [comment]
Yes, but you should provide a migration path for those migration from v12 to v13 that has this module installed. Just follow the example in the guide and it's very simple.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
¿Podrías juntar todos los commits en uno?

**Comment by AntoniRomera** [comment]
Ahora lo hago

**Comment by AntoniRomera** [comment]
All changes done, all commits merged in one

**Pull request merged**
