### PR TITLE
[14.0][MIG] account_check_report: Migration to 14.0

### PR DESCRIPTION
**Pull request by iwkse**

### CODE REVIEW

**Comment by iwkse** [comment]
@pedrobaeza I've checked the runbot and it runs correctly but it shows it failed. About the codecov, is that required for merging the PR I guess. I'm new about it, but I just renamed fields I wonder why it changed the percentage

**Comment by pedrobaeza** [comment]
```
2021-12-22 08:01:51,736 164 WARNING openerp_test py.warnings: /home/odoo/odoo-14.0/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'action_report_check_report'.
warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
```

**Comment by iwkse** [comment]
@pedrobaeza 
```
ValueError: External ID not found in the system: account.model_account_payment
```
I don't have such error locally

**Comment by pedrobaeza** [comment]
I don't know what are you talking about.

**Comment by iwkse** [comment]
> I don't know what are you talking about.

It's in the init-log of the runboat, https://runboat.odoo-community.org/api/v1/builds/b50861bed-85bb-4ffc-947a-42679c2a8d01/init-log

**Comment by pedrobaeza** [comment]
That's because you haven't declared properly the dependencies of your module in the manifest.

**Comment by iwkse** [comment]
> That's because you haven't declared properly the dependencies of your module in the manifest.

thank you @pedrobaeza
Now only codecov is complaining. Do I have to fix that too?

**Comment by pedrobaeza** [comment]
Doing tests is always advisable, but it's not an strong requirement.

Remember also to put a proper PR title like the one I have put now.

Anyways, my advisoring job is done, as I don't use this module.

**Comment by iwkse** [comment]
> Doing tests is always advisable, but it's not an strong requirement.
> 
> Remember also to put a proper PR title like the one I have put now.
> 
> Anyways, my advisoring job is done, as I don't use this module.

Ok, thank you for your information!

**Comment by iwkse** [comment]
@pedrobaeza who should I ping for the merge?

**Comment by pedrobaeza** [comment]
You can review other pull requests and ask in exchange that they review yours.

**Pull request closed without merging**
