### PR TITLE
[15.0][MIG] account_due_list_payment_mode: Migration to 15.0

### PR DESCRIPTION
**Pull request by Olageibol**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Olageibol the version in the manifest, as long as other changes needed for making it work in v15, must be done in the migration commit, not in the `[IMP] ...: black, isort, prettier` one

**Comment by LudLaf** [comment]
@Olageibol the title of your commit `2b1711bc796dec26f691bf42b8307ed92592b1b1` can be changed to `[MIG] account_due_list_payment_mode: Migration to 15.0` for it to be correct.

**Comment by LudLaf** [comment]
.

**Comment by pedrobaeza** [comment]
> @Olageibol the title of your commit `2b1711bc796dec26f691bf42b8307ed92592b1b1` can be changed to `[MIG] account_due_list_payment_mode: Migration to 15.0` for it to be correct.

No, that's not the problem. You have to extract the changes into 2 commits, as stated in the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Review by LudLaf — COMMENTED** [review]
.

**Review by LudLaf — APPROVED** [review]
Functionality is working fine. Tested on runboat.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Split the pre-commit commit and the migration one (the manifest version bump).

**Comment by LudLaf** [comment]
@Olageibol please modify the commit, so the migration can continue.

**Comment by pedrobaeza** [comment]
Superseded by #535

**Pull request closed without merging**
