### PR TITLE
[16.0][MIG] account_due_list_payment_mode: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa  TT42383

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Separate the pre-commit stuff into its own commit as stated in the migration guide. And please squash administrative commits into the generating one:

Selección_086

**Comment by Yadier-Tecnativa** [comment]
@sergio-teruel

**Review by pedrobaeza — APPROVED** [review]

**Review by enriquemartin — APPROVED** [review]

**Pull request merged**
