### PR TITLE
[13.0][MIG] account_check_printing_report_base

### PR DESCRIPTION
**Pull request by Saran440**
depend on report_wkhtmltopdf_param https://github.com/OCA/reporting-engine/pull/402

- Delete model account.register.payment. In odoo13 used account.payment instead.
- Fix Test Script for support invoice v13

### CODE REVIEW

**Comment by newtratip** [comment]
@Saran440 Could you check your CI ?

**Comment by Saran440** [comment]
@newtratip Thank you for your reviewed.
this module depend on https://github.com/OCA/reporting-engine/pull/402
Could you please review that pr?

**Comment by Saran440** [comment]
@newtratip This PR ready to review. Could you review please?

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Comment by pedrobaeza** [comment]
There's another PR for migrating this to v13 in #351, that includes some improvements done in v12. You have priority, as yours was published before, but I wonder if it's OK for you to review and approve the other instead. If not, we can merge this and do a later PR synchronizing this with v12.

**Comment by Saran440** [comment]
@pedrobaeza Okay, I will test and review pr #351

**Pull request closed without merging**
