### PR TITLE
[12.0] [MIG] Account Payment Return Import SEPA PAIN

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
This PR needs #215 to work (added in Travis config).

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
You can rebase this one

**Comment by ThomasBinsfeld** [comment]
@pedrobaeza Rebased

**Review by pedrobaeza — APPROVED** [review]

**Comment by ecino** [comment]
How come this is merged but the module `account_payment_return_import_sepa_pain` is not visible in the repository ??

**Comment by pedrobaeza** [comment]
It was renamed.

**Comment by ecino** [comment]
What's the new name please?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/account-payment/tree/12.0/account_payment_return_import_iso20022

**Pull request merged**
