### PR TITLE
[14.0][MIG] account_cash_invoice from 13.0 to 14.0

### PR DESCRIPTION
**Pull request by acsonefho**

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]
Code review and functionnal tests

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM

**Comment by dsolanki-initos** [comment]
Hi, @joao-p-marques Can we mere it?

**Comment by dsolanki-initos** [comment]
Hi, @joao-p-marques Can we mere it?

**Comment by olgamarcocb** [comment]
Can you check the migration, please? #476

**Pull request merged**
