### PR TITLE
[14.0][ADD] account_payment_paired_internal_transfer

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Add a new module to allow to make internal transfers with only one move.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by TheCloneMaster** [comment]
Hi, I tried this and works perfect.
Accountants loved to have it back as it was in v13...
Any possibility to merge?

**Comment by alan196** [comment]
@TheCloneMaster You can approve this PR in the `Files Changed` section

**Review by EduardoJarsa — APPROVED** [review]
The module is necessary  in this repository. Go ahead whit this changes.

**Review by ps-tubtim — APPROVED** [review]
Code and Functional test LGTM.

**Pull request merged**
