### PR TITLE
7.0 account voucher default writeoff

### PR DESCRIPTION
**Pull request by joaoalf**
This PR add the new module account_voucher_default_writeoff that changes thes payment mode to with writeoff when there's a writeoff amount.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the module, but I think this is a litle functionality that doesn't deserve a module, because it's only one-click distance for user.

What the others think?

**Comment by joaoalf** [comment]
Actually, this one click is a source of constant error in many of our clients. With the writeoff option there's the account field that became required so the user cannot finish the voucher without declaring the proper account for the difference value.

**Comment by pedrobaeza** [comment]
It's a good motivation indeed. Let's see what others think.

**Comment by joaoalf** [comment]
Sure. Thanks for your comments.

**Comment by eLBati** [comment]
LGTM :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
