### PR TITLE
[14.0][FIX] oca_dependencies

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Comment by GSLabIt** [comment]
should fix https://github.com/OCA/account-payment/issues/616

**Comment by francesco-ooops** [comment]
@GSLabIt rebase?

**Comment by francesco-ooops** [comment]
@etobella could you merge this one as well? it's a fix for an old reference error merged here: https://github.com/OCA/account-payment/pull/453/files#r790485920

**Comment by francesco-ooops** [comment]
thanks! ☺️

**Pull request merged**
