### PR TITLE
[16.0][MIG] account_payment_term_extension

### PR DESCRIPTION
**Pull request by anothingguy**
- since v16, Odoo now supports months natively, but not weeks and not some other features of this module, so it's still worth migrating it
- option `after_invoice_month` can be used alternatively with flag `end_month` in v16

### CODE REVIEW

**Comment by pablontura** [comment]
Functional validation LGTM

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
Hello @anothingguy , could you have a look at the pre-commit?

**Comment by cyrilmanuel** [comment]
LGTM : 
pre-commit can be resolve regarding this : 

https://github.com/OCA/oca-addons-repo-template/issues/185

create new PR:  checkout the branch (eg: 16.0) fork it and run copier -f update

**Review by cyrilmanuel — APPROVED** [review]

**Comment by StephaneMangin** [comment]
Hello @anothingguy , could you have a look at the pre-commit please?

**Comment by anothingguy** [comment]
> Hello @anothingguy , could you have a look at the pre-commit please?

Hello @StephaneMangin, pre-commit is green now

**Comment by simahawk** [comment]
@anothingguy next time, please, fix the module name in the title of the PR: it makes easier to find it while searching for PRs.

/ocabot migration account_payment_term_extension

**Comment by rafaelbn** [comment]
This migration has an issue , we are loosing functionality:

https://github.com/OCA/account-payment/issues/656

**Pull request merged**
