### PR TITLE
9.0[MIG] account_payment_return_import: Migrate from 8.0 to v9.0

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash commit history and reorder commits, because there are 2 commits for 9.0 migration. Have you merge any branch (you mustn't)?

**Comment by pedrobaeza** [comment]
Sorry, I haven't seen that you are including account_payment_return. You should warn that on the description, and put WIP or something in the title.

**Comment by pedrobaeza** [comment]
Rebased on top of current 9.0

**Review by pedrobaeza — APPROVED** [review]
Working on several environments

**Comment by pedrobaeza** [comment]
Can you include some tests for not dropping coverage?

**Comment by pedrobaeza** [comment]
@chienandalu Please review this one

**Review by chienandalu — APPROVED** [review]
I included on v10 (migrated from this PR) a basic csv importer that maybe could be backported to improve coverage and tests.

**Comment by pedrobaeza** [comment]
Well, this time we are going to merge as is, as our main target is v10. If someone wants to backport it, he/she can open another PR.

**Pull request merged**
