### PR TITLE
[11.0] [MIG] account_check_printing_report_base

### PR DESCRIPTION
**Pull request by etobella**
Migration to 11.0
Dependencies:
- [x] report_wkhtmltopdf_param https://github.com/OCA/reporting-engine/pull/182

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ursais you had this module assigned...

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review

**Comment by JordiBForgeFlow** [comment]
@etobella The dependency module report_wkhtmltopdf_param has now been merged. Can you remove from oca_dependencies.txt, and squash the commits?

**Comment by JordiBForgeFlow** [comment]
@max3903 I assume that you're good to go with this module going forward.

**Comment by etobella** [comment]
@jbeficent dependencies have been modified.

**Review by rgarnau — APPROVED** [review]
LGTM :+1:

**Pull request merged**
