### PR TITLE
[14.0][MIG] account_payment_term_extension

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include #382

**Comment by pedrobaeza** [comment]
I have found a serious inconsistency in UI with the PR, so added a fix directly in 55e57ad6671476fc3bff00a61e570c654fa9144e.

I can align everything in a new PR if you prefer.

**Comment by alexis-via** [comment]
@pedrobaeza yes, go ahead, no problem !

**Comment by pedrobaeza** [comment]
Superseded by #385

**Pull request closed without merging**
