### PR TITLE
[12.0][ADD] account_payment_multi_deduction

### PR DESCRIPTION
**Pull request by kittiu**
This module extend invoice(s)'s register payment feature,
from "Mark invoice as fully paid" with a single writeoff amount,
to "Mark invoice as fully paid (multi deduct)" which allow multiple deduction amounts.

**Note:** We use the word "Deduction", as the diff amount can be anything not only to writeoff.

### CODE REVIEW

**Comment by kittiu** [comment]
This module is ready for review.

**Comment by kittiu** [comment]
@rousseldenis :)

**Comment by kittiu** [comment]
Can this one get merged?

**Review by Saran440 — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Pull request merged**
