### PR TITLE
[13.0][FIX] account_check_printing_report_base: mistypo in args

### PR DESCRIPTION
**Pull request by i-vyshnevska**

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by bodedra — CHANGES_REQUESTED** [review]
Would you please fix this:

> TypeError: to_currency() got an unexpected keyword argument 'separator'

> Module account_check_printing_report_base: 0 failures, 1 errors

**Comment by i-vyshnevska** [comment]
> TypeError: to_currency() got an unexpected keyword argument 'separator'

that is exactly the goal of this PR
I don't really understand why it fails, look more like the wrong lib
https://github.com/savoirfairelinux/num2words/blob/8cc0e245961734510bcb1151cef7facb012855d2/num2words/base.py#L266

**Comment by bodedra** [comment]
Yes. Would you please compare your lib version and propose that change as well.

**Comment by i-vyshnevska** [comment]
ok current repo fixed travis error comes from bank-payment will check and open PR there
https://github.com/OCA/bank-payment/pull/803

**Comment by i-vyshnevska** [comment]
@bodedra can you pls the test green now

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by dreispt — APPROVED** [review]

**Pull request merged**
