### PR TITLE
[14.0][MIG] account_check_printing_report_sslm102

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:
- https://github.com/OCA/account-payment/pull/627

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please rebase.

**Comment by JasminSForgeFlow** [comment]
> Please rebase.

Done, Thanks

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Pull request merged**
