### PR TITLE
[8.0] [ADD] account_payment_return_import

### PR DESCRIPTION
**Pull request by pedrobaeza**
# 
# Account Payment Return Import

This module adds a generic wizard + methods to import payment return file
formats.

It's only the base to be extended by another modules.

Multiple payment return files contained in a zip are also supported.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @rafaelbn @sergio-teruel @carlosdauden

**Comment by rafaelbn** [comment]
Thanks :+1:

**Comment by sergio-teruel** [comment]
👍

**Comment by pedrobaeza** [comment]
As I have only taken the branch and complete it for OCA, I give my :+1: to the rest of the code and merge for the last PR depending in this one.

**Pull request merged**
