### PR TITLE
[14.0][FIX] account_cash_discount_payment

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional tests

**Comment by dsolanki-initos** [comment]
@francoisdelarbre Could you review this pull?

**Review by flotho — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
@dreispt Can we merge this?

**Comment by dsolanki-initos** [comment]
It would be great if we could merge this PR

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
