### PR TITLE
[MIG] account_cash_invoice: migration to 13.0

### PR DESCRIPTION
**Pull request by etobella**
This PR finishes the migration from #392 

Tests have been improved

@acsonefho

### CODE REVIEW

**Review by albariera — APPROVED** [review]
Technical review LGTM :+1:

**Comment by etobella** [comment]
@acsonefho Can you review so the necessary reviews will be here? :wink:

**Review by acsonefho — APPROVED** [review]
Code LGTM :+1:

**Comment by etobella** [comment]
@OCA/banking-maintainers I think this is ready for merge :wink:

**Pull request merged**
