### PR TITLE
[16.0][mig] account payment batch process, superseed w/ test

### PR DESCRIPTION
**Pull request by robinkeunen**
Superseeding https://github.com/OCA/account-payment/pull/690 adding a simple unit test

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]
I did a minimal functional test of the wizard and it worked. 
I have a difficulty understanding what functionality this module brings though, since there is already a list action "register payments". But I am sure I am missing something.

**Review by remytms — APPROVED** [review]
LGTM

**Review by MaurizioPellegrinet — COMMENTED** [review]
Hi,I want to test this PR but the runboat is pending

**Comment by JordiBForgeFlow** [comment]
@robinkeunen can you try to rebase, and see if runboat can be rebuilt?

**Comment by robinkeunen** [comment]
@JordiBForgeFlow here you go :-)

**Review by MaurizioPellegrinet — APPROVED** [review]
Functional test: OK

**Pull request merged**
