### PR TITLE
[14.0] [account_payment_term_extension] [FIX] error computing months …

### PR DESCRIPTION
**Pull request by andreampiovesana**
…and weeks

fix computing months and weeks

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
functional test locally at the end of the month 30 + 60 days are ok for me

**Review by MarcoCalcagni — APPROVED** [review]

**Review by jado95 — APPROVED** [review]

**Review by TheMule71 — APPROVED** [review]
LGTM

**Comment by StefanRijnhart** [comment]
Please install the pre-commit hooks in your local git repo and amend the commit to fix the pre-commit check (or fix the code manually, as long as the check succeeds).

Also squash commits, because the OCA gitbot does not know how to do that yet.

(sorry, closed the pull request by accident)

**Comment by StefanRijnhart** [comment]
@acsonefho care to review this one? It's a change in your original bugfix of https://github.com/OCA/account-payment/pull/369

**Review by acsonefho — APPROVED** [review]
Code LGTM

**Comment by StefanRijnhart** [comment]
Thank you @acsonefho! Then it's just the pre-commit and the squashing @andreampiovesana

**Review by tosolini — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge please

**Comment by StefanRijnhart** [comment]
Please squash your commits first, and then we can merge quickly indeed.

**Comment by andreampiovesana** [comment]
can you merge this fix!

**Comment by pedrobaeza** [comment]
Please squash your commits into one.

**Pull request merged**
