### PR TITLE
[14.0][ADD] account_payment_cancel_confirm

### PR DESCRIPTION
**Pull request by ps-tubtim**
Depends on,

- [x] https://github.com/OCA/server-ux/pull/297

This module extend `base_cancel_confirm` to make cancel confirmation with cancel reason (none / optional / requried).

### CODE REVIEW

**Review by kittiu — APPROVED** [review]
LGTM

**Comment by Saran440** [comment]
We can't split module payment and move because payment cancel depend on cancel journal entries and it need reason cancel.

I think this PR should be move on https://github.com/OCA/account-invoicing/pull/872

**Comment by kittiu** [comment]
Yes, I think this is not needed. payment and invoice are sharing object in v14.
@ps-tubtim

**Comment by ps-tubtim** [comment]
Move to https://github.com/OCA/account-invoicing/pull/872

**Pull request closed without merging**
