### PR TITLE
[12.0][MIG] account_check_report

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: strptime() argument 1 must be str, not datetime.date
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_679_427
  File "<template>", line 2, in body_call_content_426
  File "<template>", line 3, in body_call_content_425
  File "<template>", line 4, in foreach_424
  File "/home/odoo/build/OCA/account-payment/account_check_report/report/report_helper.py", line 19, in _format_date_to_partner_lang
    date = datetime.strptime(str_date, DEFAULT_SERVER_DATE_FORMAT).date()
TypeError: strptime() argument 1 must be str, not datetime.date

Trying to print check on runbot: http://3395537-290-a4b288.runbot2.odoo-community.org/web?debug=1#id=2&action=140&active_id=7&model=account.payment&view_type=form&menu_id=82

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Duplicated

**Comment by MiquelRForgeFlow** [comment]
@aheficent fixed, ready to review

**Comment by AaronHForgeFlow** [comment]
Refunds must show

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test + code review. Nice!

**Review by AdriaGForgeFlow — COMMENTED** [review]
Could you use this PR to update copyright and author to ForgeFlow?

**Comment by MiquelRForgeFlow** [comment]
@AdriaGForgeFlow I think it's better to do that in another PR affecting the full repo.

runbot is green :)

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
