### PR TITLE
[ADD]account_due_list_edit_inline: editing name and date inline

### PR DESCRIPTION
**Pull request by odooNextev**

### CODE REVIEW

**Review by GSLabIt — APPROVED** [review]

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Comment by francesco-ooops** [comment]
@OCA/banking-maintainers could this be merged? thanks!

**Comment by francesco-ooops** [comment]
@etobella anything against this?

**Comment by etobella** [comment]
Why aren't you adding it directly to the base module? It hasn't have too much sense IMO.

**Comment by francesco-ooops** [comment]
@etobella we didn't want to change formatting of "date" column single-handedly for everyone... but we wouldn't mind adding it to base module. 

Do you think we should add an extra column and let user choose which one to use? or what do you suggest?

**Comment by francesco-ooops** [comment]
@etobella shall we merge as it is?

**Comment by francesco-ooops** [comment]
@etobella ping :)

**Comment by etobella** [comment]
Yes, I think we should merge it as a lot of modules have been done for this... I would propose to merge them in a single module on 16 or 17, but not right now....

/ocabot merge nobump

**Pull request merged**
