### PR TITLE
[15.0][MIG] account_due_list_payment_mode: Migration to version 15.0

### PR DESCRIPTION
**Pull request by LudLaf**
@Tecnativa  TT36417

Migration of `account_due_list_payment_mode` to version 15.0, which will supersede PR #518

### CODE REVIEW

**Comment by LudLaf** [comment]
@pedrobaeza 
@cesar-tecnativa 
@chienandalu  
please review.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@Olageibol you can check this one?

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
