### PR TITLE
[14.0] mig account_cash_discount_base

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
Hello @Cedric-Pigeon it would be nice if could you review this module.

**Comment by hkapatel-initos** [comment]
Hello @Cedric-Pigeon it would be nice if could you review this module.

**Review by fshah-initos — APPROVED** [review]
Code review and functional tests

**Comment by dsolanki-initos** [comment]
Can someone please review this PR?

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by Cedric-Pigeon** [comment]
@dsolanki-initos done ;-)

**Comment by dsolanki-initos** [comment]
Hi, @joao-p-marques Can we mere it?

**Review by joao-p-marques — APPROVED** [review]

**Pull request merged**
