### PR TITLE
[FIX] account_payment_term_discount: cannot add extra amount

### PR DESCRIPTION
**Pull request by atchuthan**
If the payment difference is less than the invoice amount, it will follow the base functionality.
If the payment difference is in between discounted amount and invoice amount or payment difference is zero, the payment will be discounted amount.
If the payment difference is greater than the invoice amount, it will follow the base functionality.

Related Issue: https://github.com/OCA/account-payment/issues/470

cc: @SodexisTeam

### CODE REVIEW

**Comment by atchuthan** [comment]
@dreispt ping

**Comment by amkarthik** [comment]
Looks good to me

**Review by amkarthik — APPROVED** [review]

**Comment by atchuthan** [comment]
@OCA/oca-contributors please review

**Review by dreispt — APPROVED** [review]
LGTM

**Comment by MiquelRForgeFlow** [comment]
please, forward port to v15.

**Pull request merged**
