### PR TITLE
[10.0][add][account_check_printing_report_sslm102]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module allows you to print SSLM102 lined checks.

See https://www.google.es/search?q=sslm102

image

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
refactor based on https://github.com/OCA/account-payment/pull/261

**Review by AaronHForgeFlow — APPROVED** [review]
Works in production environment :smile:

**Comment by AaronHForgeFlow** [comment]
@mreficent still red, can you check?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Works good

**Review by HviorForgeFlow — APPROVED** [review]
Functional review
LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Ready to merge

**Comment by AaronHForgeFlow** [comment]
Ready to merge

**Pull request merged**
