### PR TITLE
[17.0][MIG] account_payment_return: Migration to version 17.0

### PR DESCRIPTION
**Pull request by carlos-lopez-tecnativa**
@Tecnativa TT49281

### CODE REVIEW

**Comment by carolinafernandez-tecnativa** [comment]
I have tested on runboat and only one comment:

If i duplicate one customer payment return confirmed, Reference to the created journal entry is copied from original customer payment return. This field should be empty when copying it.

image

**Comment by carlos-lopez-tecnativa** [comment]
> I have tested on runboat and only one comment:
> 
> If i duplicate one customer payment return confirmed, Reference to the created journal entry is copied from original customer payment return. This field should be empty when copying it.

@carolinafernandez-tecnativa  Good catch! I made the change. Please update your review. Thanks!

**Review by carolinafernandez-tecnativa — APPROVED** [review]
LGTM Thanks :)

**Review by smcqueen81 — APPROVED** [review]
Ok functional

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Thanks for the improvements and fixes:

/ocabot merge nobump

You can backport to 15/16 the copy=False patch.

**Pull request merged**
