### PR TITLE
[14.0][MIG] account_payment_term_partner_holiday

### PR DESCRIPTION
**Pull request by antoniospneto**
This is a default migration, and it doesn't require scripts for major versions.

### CODE REVIEW

**Comment by antoniospneto** [comment]
Brought over the improvements from version 15.0 implemented by @LudLaf in PR #523 as they are also valid here.
PR ready for review.

cc @rvalyi @marcelsavegnago @mileo

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by percevaq** [comment]
LGTM

**Review by felipemotter — APPROVED** [review]

**Comment by antoniospneto** [comment]
cc @OCA/banking-maintainers

**Review by etobella — APPROVED** [review]
No real changes on the migration

**Comment by percevaq** [comment]
Collaborating and thanking OCA

**Pull request merged**
