### PR TITLE
[13.0][ADD] sale_payment_term_security: New module

### PR DESCRIPTION
**Pull request by victoralmau**
New module

Locked by:
- [x] `account_payment_term_security`: https://github.com/OCA/account-payment/pull/577

Please @CarlosRoca13 and @pedrobaeza can you review it?

@Tecnativa TT41273

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please rebase to get a proper CI result

**Comment by victoralmau** [comment]
Rebase done.

**Comment by victoralmau** [comment]
Ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
