### PR TITLE
[13.0] [MIG] account_early_payment_discount

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
pls squash `fixup!` commits

**Comment by grindtildeath** [comment]
As this module doesn't do anything on itself, shouldn't it be merged with https://github.com/OCA/account-reconcile/pull/356 ?

**Review by rafaelbn — APPROVED** [review]
👍

**Comment by rafaelbn** [comment]
Hello @simahawk , could you check this and merge it? 😄

**Comment by dreispt** [comment]
I think pre-commit is failing.

**Pull request closed without merging**
