### PR TITLE
11.0 mig account partner reconcile

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Supersedes https://github.com/OCA/account-payment/pull/181

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
I am proposing this PR, that was migrated by @jaumeplanas in the first place. My review is :+1:

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza regarding moving to OCA/account-reconcile, could be but it was proposed in v10 in this repo, that also makes sense. I propose not to move, given the mess it turns to be in the odoo apps store when you move modules across repos.

**Comment by pedrobaeza** [comment]
OK

**Comment by JordiBForgeFlow** [comment]
Mergingbas it is a trivial migration and looks good

**Pull request merged**
