### PR TITLE
[12.0][FIX] - payment return reason csv file missing in manifest

### PR DESCRIPTION
**Pull request by sbejaoui**
This PR fixes:
- Missing quotes in L216 and 217 to escape comma used in name
- Payment return reason csv file missing in manifest

### CODE REVIEW

**Comment by sbejaoui** [comment]
@ThomasBinsfeld, can you check this please

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Not sure if we already discussed this, but isn't a lot of reasons to be loaded?

**Comment by ThomasBinsfeld** [comment]
@pedrobaeza It's all the reasons defined by ISO20022, assuring that all return codes we receive will be well interpreted by the module.

**Comment by pedrobaeza** [comment]
Yeah, I know, but maybe it's overwhelmed. Let's see what people says.

**Review by pedrobaeza — APPROVED** [review]

**Pull request closed without merging**
