### PR TITLE
[14.0][MIG]Migrated account_payment_credit_card

### PR DESCRIPTION
**Pull request by Freni-OSI**
Migrated account_payment_credit_card from v13 to v14

### CODE REVIEW

**Comment by Freni-OSI** [comment]
Needs review
CC @patrickrwilson

**Review by patrickrwilson — APPROVED** [review]
Code review, looks good. LGTM

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM

**Comment by dsolanki-initos** [comment]
Hi, @joao-p-marques Can we mere it?

**Comment by dsolanki-initos** [comment]
Hi, @joao-p-marques Can we mere it?

**Pull request merged**
