### PR TITLE
[16.0][MIG] account_payment_return: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT43212

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @pedrobaeza , @sergio-teruel

**Review by pedrobaeza — COMMENTED** [review]
Thanks for this. Tried on runboat, it almost work.

- I pay an invoice, and the payment info says that it was paid in the date.
- I make the return, the invoice is not paid, and the payment info says that it was returned on the date of the return.
- The problem comes when I pay it again. The second payment doesn't appear.

Can you please check it?

**Comment by Yadier-Tecnativa** [comment]
Done

**Review by stefan-tecnativa — APPROVED** [review]
Functionally tested. LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
