### PR TITLE
[15.0][MIG] account_check_payee

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migrate and continue from https://github.com/OCA/account-payment/pull/602

cc @ps-tubtim @bizzappdev

### CODE REVIEW

**Review by cmcreamm — APPROVED** [review]
Functional test

**Review by ps-tubtim — APPROVED** [review]

**Review by bizzappdev — APPROVED** [review]

**Comment by Saran440** [comment]
@OCA/banking-maintainers Hi, Can you help review and merge, please.

**Comment by etobella** [comment]
Can you rebase in order to fix pre-commit?

**Comment by Saran440** [comment]
updated. Thank you for reviewed.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
