### PR TITLE
[ADD] account_move_line_payment: simple partial overdue payment flow

### PR DESCRIPTION
**Pull request by yajo**
New module that simplifies the use case of registering partial invoice payments.

@moduon MT-5071

### CODE REVIEW

**Review by Gelojr — APPROVED** [review]
LGTM Very nice job @yajo 
https://www.loom.com/share/7a9a98ccbbfd4f5a8b4de43265eaef33?sid=55eb7e93-e26e-4a44-81f4-0d0b3fc0bb12

https://www.loom.com/share/5269c180efb949a8a29f9dd12fafc141?sid=9dc00eda-9539-4808-abbe-7e1df694fa22

**Review by rafaelbn — COMMENTED** [review]
Please @yajo review what is already done in 17 to make migration direct

Also the module name in my head is more like `account_move_line_payment`

**Review by fcvalgar — APPROVED** [review]
Functional review.
LGTM.

Thak you @yajo

**Comment by yajo** [comment]
New changes:
- Module renamed.
- Added to roadmap that this doesn't need fwports.

**Review by rafaelbn — APPROVED** [review]
Tested! 👍🏼 

As said, this is already in Odoo 17, so this module will not be migrated!

Thank you! ❤️

**Comment by rafaelbn** [comment]
Hello @OCA/banking-maintainers ,

This a backport of a Odoo 17 new menu and functionality and [it doesn't need yo be migrated](https://github.com/OCA/account-payment/pull/709/files#diff-27dd05e034b48cc0521ce2e5aeec7bbcb7cf14fab9b9b3f2c5cec3861ec820b0R98).

Please could you take a look?

Thanks
Regards,
Rafael

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by yajo** [comment]
Hello @etobella @HaraldPanten @JordiBForgeFlow. This is a practical module that has been working in production for 4 months already. Could somebody hit the merge button? 😇 Thanks!

**Comment by HaraldPanten** [comment]
@yajo @rafaelbn merged 👍

**Pull request merged**
