### PR TITLE
[ADD] module account_payment_credit_card

### PR DESCRIPTION
**Pull request by bodi000**
backport from v10

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should preserve commit history using the technical method in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0, but inverting branches order.

**Comment by bodi000** [comment]
Pedro,

Thank you for your feedback, and sorry about my ignorance. Now how should I go about it? I close this PR and open a new one with the new branch I prepared? Or bring the branch here? 

Thank you in advance!
B

**Comment by bodi000** [comment]
I have this branch ready:
[https://github.com/bodi000/account-payment/tree/9.0-mig-account_payment_credit_card](https://github.com/bodi000/account-payment/tree/9.0-mig-account_payment_credit_card)

**Comment by pedrobaeza** [comment]
@bodi000 if you want, you can overwrite this branch for updating the PR. You just need to:

- delete locally the branch with this name that is wrong
- git checkout -b <this_branch_name> starting from the correct branch
- git push -f over your remote.
- this PR will be auto-update with new code

**Comment by bodi000** [comment]
@pedrobaeza Could you please tell me if something stops this for merging? Thank you

**Comment by pedrobaeza** [comment]
Hi @bodi000, there should be reviewers for it (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#72review). You can review others PRs and ask in exchange that they review yours.

**Pull request closed without merging**
