### PR TITLE
[14.0][FIX] account_payment_batch_process_discount.

### PR DESCRIPTION
**Pull request by Murtaza-OSI**
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3659, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3046, in write
    return self.write_batch([(records, value)])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3067, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3218, in write_real
    comodel.browse(command[1]).write(command[2])
  File "/odoo/addons/account_payment_batch_process_discount/models/account_payment_term_line.py", line 17, in write
    invoice_ids = self.env["account.move"].search(
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1702, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4490, in _search
    query = self._where_calc(args)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4246, in _where_calc
    return expression.expression(domain, self).query
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 654, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field account.move.payment_term_id in leaf ('payment_term_id', '=', 170)

### CODE REVIEW

**Review by smangukiya — APPROVED** [review]

**Review by dnplkndll — APPROVED** [review]
Any reason this required fix is not getting merged?
I guess only comes up on a discount change.

**Comment by dnplkndll** [comment]
@Murtaza-OSI  looks like a simple fix name fix.

**Review by dnplkndll — CHANGES_REQUESTED** [review]
see https://github.com/OCA/account-payment/pull/488
2 more

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Comment by patrickrwilson** [comment]
ping @dreispt

**Pull request merged**
