### PR TITLE
[FIX] account_payment_term_discount: Vendor Bill discounts use wrong account

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by dreispt** [comment]
@max3903 Can you review please?

**Comment by RLeeGML** [comment]
@dreispt  Can you resolve the merge conflict here? Otherwise, LGTM

**Comment by dreispt** [comment]
You can take over if you like, I don't plan to work on this the next couple of weeks.

**Review by RLeeGML — APPROVED** [review]
Code review looks good

**Comment by RLeeGML** [comment]
@max3903  Can you review?

**Pull request merged**
