### PR TITLE
[14.0] [mig] account_cash_discount_payment

### PR DESCRIPTION
**Pull request by fshah-initos**
dependencies
account_cash_discount_base #451

### CODE REVIEW

**Comment by xavier-bouquiaux** [comment]
Hi, <br/>
In order to set travis in green could-you create a test-requirement.txt with the following dependency ? <br/>
https://github.com/initOS/account-payment/tree/14.0-mig-account_cash_discount_base <br/>
Kind Regards <br/>
Xbo.

**Comment by hkapatel-initos** [comment]
it would be great if 

> Hi, In order to set travis in green could-you create a test-requirement.txt with the following dependency ? https://github.com/initOS/account-payment/tree/14.0-mig-account_cash_discount_base Kind Regards Xbo.

Hello, Travis is happy it would be great if you add reviews here.

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional tests

**Comment by fshah-initos** [comment]
It would be nice if someone adds reviews here.

**Comment by dsolanki-initos** [comment]
It would be nice if someone adds reviews here.

**Comment by dsolanki-initos** [comment]
@xavier-bouquiaux it would be nice if we add reviews here.

**Comment by hkapatel-initos** [comment]
Hi, the issue is resolved Can you please try to merge it again?

**Pull request merged**
