### PR TITLE
[10.0][MIG] account_partner_reconcile

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Added a test just for the pleasure of seeing the PR full greenified.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
tested on runbot + code review :+1: 

BTW, nice tests  :ok_hand:

**Comment by pedrobaeza** [comment]
Shouldn't this be on OCA/bank-statement-reconcile?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza This has nothing to do with the bank statement, it is related to manual payments.

**Review by Cedric-Pigeon — APPROVED** [review]
Code review

**Comment by pedrobaeza** [comment]
OK then

**Pull request merged**
