### PR TITLE
[ADD] payment_sisow

### PR DESCRIPTION
**Pull request by hbrunn**
Sisow Payment Acquirer
======================

This module was written to support payments via the Dutch payment acquirer [Sisow](https://sisow.nl)
in Odoo.

Configuration
=============

To configure this module, you need to:

- go to Accounting / Configuration / Payments / Payment Acquirers
- find the record with `provider` ``Sisow``
- fill in your `merchant ID` and your `merchant key` as provided by Sisow
- after testing, set the field `Environment` to ``Production`` and click the top right button to make the payment acquirer visible on the website

Known issues / Roadmap
======================

* currently, this module only supports Sisow's iDeal implementation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@hbrunn is this going to be finished?

**Comment by hbrunn** [comment]
it's in production for a customer. But given there doesn't seem much interest in this and I won't fix the tests any time soon, we can just as well close this and reopen whenever we commits more time to this

**Comment by pedrobaeza** [comment]
I'm seeing that the tests that are failing are inside the module. Maybe better to remove them and let this comes to this branch?

**Comment by hbrunn** [comment]
let's not water down OCA's quality standards. Code without tests is not mergable in my book, so I rather close this

**Comment by pedrobaeza** [comment]
OK, I also prefer with tests, but remember that it's not an OCA requirement right now.

**Comment by hbrunn** [comment]
oh, let's clarify this. I read [Tests or scenario are not all green and/or not adapted](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#it-makes-sense-to-be-picky-in-the-following-cases) as 'when coveralls is red, no merge' and that's also what I execute in 'my' repositories which gives me unpleasant discussions every now and then.

I think it's a good thing to demand that new code has at least the coverage as the repo, so I'm fine with the way it is. But if you (and probably the board) disagree with this reading, then I think we should change the wording.

**Comment by pedrobaeza** [comment]
No, I totally agree with you of course. I would try to go to 100% coverage (see https://github.com/OCA/vertical-association that it's totally ours), but again there's the argument about not difficulting newcomers contribution and so on...

**Pull request closed without merging**
