### PR TITLE
[17.0][FIX] account_payment_term_extension: Add selection options translatable

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please take the occasion to rename the method to the guideline `_selection_delay_type`.

**Comment by ramiadavid** [comment]
@pedrobaeza Why don't all the terms to translate appear on weblate? In the .pot file they do appear, but in the .po of the languages, there are many that do not appear, and I don't know how to add them, since it says that it is 100% translated when it is not.
image
image

**Comment by pedrobaeza** [comment]
Can you mention one specifically? The bot, after a merge, regenerate the POT file, and then reapply the POT on each .po, so they should be synchronized. Maybe something in the middle has failed.

**Comment by ramiadavid** [comment]
In the images you can see that in English there are 46 terms vs 33 in Spanish
For example "Days and Months" in spanish in Spanish it is not

**Comment by pedrobaeza** [comment]
@sbidoul do you know why there's no PO update after POT regeneration?

**Review by pedrobaeza — APPROVED** [review]

**Comment by neo-oien** [comment]
Hello,

I've detected the same problem. 
Option values for 'delay_type' field don't appear in .PO file and there is no way to translate them.

imagen

Best regards

**Pull request closed without merging**
