### PR TITLE
[15.0][MIG] account_payment_multi_deduction

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
Functional Test: Ok.

**Review by newtratip — APPROVED** [review]

**Comment by kittiu** [comment]
Hello, maintainer, can you help please ;)

**Comment by Saran440** [comment]
This PR cherry-pick https://github.com/OCA/account-payment/pull/490 and https://github.com/OCA/account-payment/pull/609

**Pull request merged**
