### PR TITLE
[13.0][MIG] account_payment_show_invoice

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This is the migration of module account_payment_show_invoice.

To make the migration of this module I have simplified the previous one a lot since in version 13.0 there is already a field that maintains odoo, called "communication" maintains the references to the invoices from the payment.

I just had to insert this field in the views and put it as a search field, so we have a functionality that did not exist before.

### CODE REVIEW

**Comment by Zar21** [comment]
imagen
In Invoicing/Vendors/Payments the column communication is showed twice times but in Invoicing/Vendors/Payments shows correctly 
imagen

**Comment by manuelcalerosolis** [comment]
> imagen
> In Invoicing/Vendors/Payments the column communication is showed twice times but in Invoicing/Vendors/Payments shows correctly
> imagen

Fixed! Thanks for you review.

**Review by fshah-initos — APPROVED** [review]
Code review and Functional tests. LGTM

**Comment by fshah-initos** [comment]
can this be merged?

**Comment by fshah-initos** [comment]
It woul dbe great if somone could add reviews and merge it

**Comment by fshah-initos** [comment]
It would be great if we could get the reviews and merge this PR.

**Comment by fshah-initos** [comment]
It would be great if we could get the reviews and merge this PR.

**Comment by fshah-initos** [comment]
It would be great if we could merge this PR.

**Comment by fshah-initos** [comment]
@OCA/accounting-maintainers can you please merge this PR?

**Comment by fshah-initos** [comment]
@tbaden It would be great if you could add reviews here

**Comment by fshah-initos** [comment]
It would be great if you could add reviews here

**Comment by MiquelRForgeFlow** [comment]
@manuelcalerosolis could you rebase this PR?

**Review by tbaden — APPROVED** [review]
Code LGTM

**Comment by fshah-initos** [comment]
It would be nice if we could merge it

**Comment by AaronHForgeFlow** [comment]
@dreispt there is a typo in your message, that is why the bot did not start, could you retry?

**Pull request merged**
