### PR TITLE
[14.0][IMP] account_payment_batch_process: clean wizard layout

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by francesco-ooops — APPROVED** [review]
Functional ok, layout fixed

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers wdyt?

**Comment by grindtildeath** [comment]
@GSLabIt @francesco-ooops 
Adding screenshots before / after in PR description would help getting this merged faster. :wink:

**Comment by GSLabIt** [comment]
> @GSLabIt @francesco-ooops Adding screenshots before / after in PR description would help getting this merged faster. 😉

before pr: 

Screenshot 2024-06-12 alle 09 47 56


pr:

Screenshot 2024-06-12 alle 09 48 52

**Comment by francesco-ooops** [comment]
@grindtildeath what do you think?

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
