### PR TITLE
[15.0][MIG] account_payment_widget_amount

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @ChrisOForgeFlow do you mind rebasing, please? I would like to see the checks. THX!

**Review by HaraldPanten — APPROVED** [review]
It works like a charm 👍

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review :+1:

**Pull request merged**
