### PR TITLE
[8.0] Migration of account_vat_on_payment and account_voucher_cash_basis

### PR DESCRIPTION
**Pull request by tafaRU**
This PR contains the migration (without porting to the new API) of the following modules:
1. **_account_vat_on_payment**_ at the moment only present in https://github.com/eLBati/account-payment/tree/adding_account_vat_on_payment_7/account_vat_on_payment
2. **_account_voucher_cash_basis**_ from which the first one depends on

### CODE REVIEW

**Comment by tafaRU** [comment]
Anyone here knows how can I fix this: https://travis-ci.org/OCA/account-payment/jobs/40890422#L203 ?

```
2014-11-13 14:46:34,096 23705 ERROR openerp_test openerp.tools.yaml_import: onchange_partner_id() takes at most 10 arguments (11 given)
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 894, in process
self._process_node(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 905, in _process_node
self.process_record(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 329, in process_record
record_dict = self._create_record(model, fields, view_info, default=default)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 461, in _create_record
result = getattr(model, match.group(1))(self.cr, SUPERUSER_ID, [], *args)
File "/home/travis/odoo-8.0/openerp/api.py", line 237, in wrapper
return old_api(self, *args, **kwargs)
TypeError: onchange_partner_id() takes at most 10 arguments (11 given)
2014-11-13 14:46:34,097 23705 ERROR openerp_test openerp.tests: module account_vat_on_payment: an exception occurred in a test
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 64, in load_test
_load_data(cr, module_name, idref, mode, 'test')
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 118, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 895, in convert_file
convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 958, in yaml_import
yaml_interpreter.process(yaml_string)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 894, in process
self._process_node(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 905, in _process_node
self.process_record(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 329, in process_record
record_dict = self._create_record(model, fields, view_info, default=default)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 461, in _create_record
result = getattr(model, match.group(1))(self.cr, SUPERUSER_ID, [], *args)
File "/home/travis/odoo-8.0/openerp/api.py", line 237, in wrapper
return old_api(self, *args, **kwargs)
TypeError: onchange_partner_id() takes at most 10 arguments (11 given)
```

Thank you in advance.

**Comment by gurneyalex** [comment]
account.invoice was ported to the new api in v8. I believe you need to use the @api.cr_uid_ids decorator on your version for it to work properly.

**Comment by tafaRU** [comment]
@gurneyalex unfortunately build still failed, same error. Any further hints will be appreciated!

Thank you in advance.

**Comment by lepistone** [comment]
@tafaRU Give a look to tafaru#1: that should fix the problem with the 11 parameters. That showed another similar problem with another method, fixed in the next commit. After that it is still red because of other issue.

**Comment by tafaRU** [comment]
Thank you so much, @lepistone :smiley: 
Yes, I tried your branch and indeed it still fails because of other issues.

Meanwhile I merge your PR, I'm grateful :sunflower:

**Comment by tafaRU** [comment]
Two errors left:

`2014-11-14 22:24:11,834 23693 INFO openerp_test openerp.modules.loading: loading account_vat_on_payment/test/account_invoice_3.yml
2014-11-14 22:24:14,725 23693 ERROR openerp_test openerp.tools.yaml_import: AssertionError in Python code  (line 58): sales move line must be 43.48 credit, 43.48 found`

`2014-11-14 22:24:23,535 23693 INFO openerp_test openerp.modules.loading: loading account_vat_on_payment/test/account_invoice_6.yml
2014-11-14 22:24:26,893 23693 ERROR openerp_test openerp.tools.yaml_import: AssertionError in Python code  (line 57): sales move line must be 20.83 credit, 20.83 found`

Something concerning the decimal precision.
@lepistone do you by any chance know how to fix them?

**Comment by lepistone** [comment]
two ways to do that:

1.

``` python
assert abs(20.83 - credit) < 0.01, "credit is not 20.83"
```

2.

``` python
from nose.tools import *
assert_almost_equal(20.83, credit, places=2)
```

this needs `pip install nose`. `nose.tools` includes the assertions from the `unittest` module outside `TestCase` classes. See:
- https://nose.readthedocs.org/en/latest/testing_tools.html
- https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual

**Comment by tafaRU** [comment]
Thanks again @lepistone !

**Comment by tafaRU** [comment]
Yeah, finally green!!! :metal: 
Thanks a `pow(10, 6)`, @gurneyalex @lepistone

**Comment by eLBati** [comment]
:+1: LGTM
But still not clear the destiny of these modules
https://lists.launchpad.net/banking-addons-drivers/msg00142.html

**Comment by sbidoul** [comment]
@eLBati @tafaRU regarding the destiny of these modules which is a very good question indeed.

First a disclaimer: I'm not very familiar with vouchers - I always did odoo accounting without them.

There are several aspects to this topic:
- VAT on payment is indeed useful and necessary in some cases
- If my understanding is correct, vouchers will probably be removed from v9
- the OCA/bank-\* do not use vouchers

So my main question is how do you see the future of these voucher-based modules? 
Do you think they can be reimplemented without vouchers (in the future)? 
Do they conflict with modules in OCA/bank-_? 
If they don't conflict, do they work well with OCA/bank-_?

**Comment by pedrobaeza** [comment]
We should do this PR against renamed bank-payment project.

**Comment by sbidoul** [comment]
@pedrobaeza I agree if these modules do not conflict and work well with other OCA/bank-payment modules.

**Comment by eLBati** [comment]
Hello @sbidoul 

> So my main question is how do you see the future of these voucher-based modules?
> Do you think they can be reimplemented without vouchers (in the future)?

I hope in future VAT on payment will be refactored avoiding the use of vouchers. ATM this is the only solution we have. See an extended discussion at https://github.com/OCA/account-payment/pull/2

> Do they conflict with modules in OCA/bank-?

AFAIK They don't

> If they don't conflict, do they work well with OCA/bank-?

I noticed that in v8 the link between `account.bank.statement.line` and `account.voucher` is not present anymore.
So, unless we find a better solution for VAT on payment (without vouchers) for v8 already, we will probably need to re-add the link and the integration.

**Comment by eLBati** [comment]
Setting this as WIP because I'm making some tests about a based on reconciliation cash basis

**Comment by eLBati** [comment]
> Setting this as WIP because I'm making some tests about a based on reconciliation cash basis

I have not been able to do it.
Can't cover every case: partial payments, write-off, multi currency...

**Comment by ghost** [comment]
@tafaRU see https://github.com/OCA/account-payment/pull/32. This the error in your module.

**Comment by tafaRU** [comment]
thanks @dufresnedavid  
I applied your fix but a I still have some errors need to be investigated.

**Comment by eLBati** [comment]
See

```
File "/home/travis/build/OCA/account-payment/account_voucher_cash_basis/account_voucher.py", line 165, in allocated_amounts_grouped_by_invoice
context['date'] = voucher.date
```

the error seems to depend on the last commit https://github.com/tafaRU/account-payment/commit/009a93bcbb503ca26e51b4c6571d808f0be7d273

**Comment by feketemihai** [comment]
@eLBati @tafaRU Can you tell me what is the status of this pr, are you still working on it and what else is needed to be done???

**Comment by eLBati** [comment]
Hello @feketemihai , tests need to be fixed.
We planned to work on it in the next weeks.
If you want to contribute, you are welcome of course :grin:

**Comment by feketemihai** [comment]
@eLBati I took the module and local with demo data, no error regarding the tests...i don't know why on runbot hits the error on invoice 5...

**Comment by feketemihai** [comment]
@eLBati @tafaRU How is it the vat on payment treatment in Italy, in Romania it's dedicated on the partner, on customer invoice it takes the vat on payment from company, on supplier invoice it takes the vat on payment from supplier, so even if the company is not label as vat on payment, it still needs to comply because the supplier is label as vat on payment, so the tax is becomming exigible only at payment.

**Comment by feketemihai** [comment]
@eLBati @tafaRU In most of the countries this treatment depends on the turnover, so if the company(partner) exceeds the limit set in legislation, it doesn't respect the vat on payment treatment, so if you have another invoice that is not with vat on payment and some invoices from the past, you cannot use the voucher to pay them, because of the restriction that all the invoices must be with vat on payment...Can we remove this constrain ?

**Comment by eLBati** [comment]
On 14 May 2015 at 09:18, Fekete Mihai notifications@github.com wrote:

> @eLBati https://github.com/eLBati @tafaRU https://github.com/tafaRU
> In most of the countries this treatment depends on the turnover, so if the
> company(partner) exceeds the limit set in legislation, it doesn't respect
> the vat on payment treatment, so if you have another invoice that is not
> with vat on payment and some invoices from the past, you cannot use the
> voucher to pay them, because of the restriction that all the invoices must
> be with vat on payment...Can we remove this constrain ?
> 
> The constraint is: with 1 voucher you can pay invoices which are all 'vat
> on payment'. See
> https://github.com/tafaRU/account-payment/blob/8.0-account_vat_on_payment-migr/account_vat_on_payment/account_voucher.py#L35
> But with 1 voucher you can also pay 'normal VAT' invoices, if they are all
> normal.

I think removing this constraint we would compromise the feasibility of the
computation.

In case where a customer has a set of normal invoices and a set of vat on
payment invoices, in order to pay them you should create 2 distinct
vouchers.

**Comment by tafaRU** [comment]
Looks again green!!!

**Comment by eLBati** [comment]
:+1:

**Comment by feketemihai** [comment]
:+1:

**Comment by feketemihai** [comment]
@eLBati @tafaRU Will you update as well the bank statement reconciliation to record the moves for VAT on payment, since V8 doesn't use vouchers like V7?

**Comment by feketemihai** [comment]
@eLBati @tafaRU I will try to work on it in the following days, in the same manner the vouchers are, i will make a pr on this repo....

**Comment by tafaRU** [comment]
> @eLBati @tafaRU I will try to work on it in the following days, in the same manner the vouchers are, i will make a pr on this repo....

Thanks a lot, @feketemihai!

**Comment by feketemihai** [comment]
@tafaRU @eLBati Can you tell me why you use _move_payment_lines_to_shadow_entry in voucher, basically this will change the real move done by voucher so you don't see that you paid a supplier or receive a payment from customer, because that move line is moved into the shadow move...so from my point of view is not quite correct...i think we should leave the move done by voucher in the same format, and in the shadow to have the move lines for base and vat amounts from invoice lines...What do you think?

**Comment by eLBati** [comment]
Hello @feketemihai we move customer/supplier entry away from bank entry because we wanted the bank entry to contain only the bank, VAT and sales move lines. So that customer/supplier entry can be recorded on a different journal.

What do you mean with

> you don't see that you paid a supplier or receive a payment from customer

?
From voucher you can reach receivable/payable move through `shadow_move_id` field
From invoice you can reach bank move through `real_payment_move_id` on payment move line (in the payments TAB).

Maybe you could  make a PR proposing the changes which avoid to execute `_move_payment_lines_to_shadow_entry` based on a configuration flag?

**Comment by feketemihai** [comment]
@eLBati The ideea is that voucher and bank statement line moves generates the folowing move lines:
bank(cash) = receivable or payable = bank(cash),
with the _move_payment_lines_to_shadow_entry the moves are changed to
bank(cash) = income + tax or expense + tax = bank(cash), so basically you will not see the right move as for a normal invoice, so if we eliminate the method the voucher and bank statement line will be the same as the normal invoices and in the shadow move we will have income(expense) and tax moves ...

I didn't have a lot of time to work on the bank statement lines reconciliation to take in consideration the vat on payment, but i will do it soon.

**Comment by eLBati** [comment]
Hi all, do you think this can be merged?

**Comment by max3903** [comment]
:+1:

**Pull request merged**
