### PR TITLE
[WIP][ADD] Added module : osi_ippay_payment

### PR DESCRIPTION
**Pull request by Chanakya-SerpentCS**
[ADD] Added module : osi_ippay_payment

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The name mustn't include companies

**Comment by Chanakya-SerpentCS** [comment]
Already changed will push soon.

**Comment by bodedra** [comment]
@Chanakya-SerpentCS : This module is depend on another custom module `osi_add_credit_card`

CC @max3903

**Comment by Chanakya-SerpentCS** [comment]
For now closing this PR once done with the required changes. 
I will reopen it.

**Pull request closed without merging**
