### PR TITLE
[16.0][MIG] account_due_list: Migration to 16.0

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
tested (by adding the admin user in the "Show Accounting Features - Readonly" menu first)

**Review by mileo — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
@ramiadavid has this pull request the same problem about the symbolic link?

**Comment by ramiadavid** [comment]
@pedrobaeza I think it's already solved in all pull request

**Comment by pedrobaeza** [comment]
Great. I hope you switch to Linux, as Windows for Odoo is a pain...

/ocabot merge nobump

**Pull request merged**
