### PR TITLE
[13.0][MIG] account_cash_discount modules

### PR DESCRIPTION
**Pull request by benwillig**
Migration of:

- [x] account_cash_discount_base
- [x] account_cash_discount_payment
- [x] account_cash_discount_write_off

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]
LGTM (code review only).

Could you please check why runbot is red ?

**Comment by pedrobaeza** [comment]
Do you know `account_global_discount` and corresponding modules that perform the same in a general manner?

**Comment by benwillig** [comment]
> LGTM (code review only).
> 
> Could you please check why runbot is red ?

travis is fixed now

**Comment by eguane** [comment]
Hi, did you expect to backport it to v12 ?
between 80% and 90% of company in belgium using cash discount with this scenario:  deducted discount from amount total without reducing VAT base, is it possible with your module.
Rgds

**Comment by benwillig** [comment]
> Hi, did you expect to backport it to v12 ?
> between 80% and 90% of company in belgium using cash discount with this scenario: deducted discount from amount total without reducing VAT base, is it possible with your module.
> Rgds

Not at the moment, but I think it shouldn't be so hard to migrate this from 10.0 to 12.0

**Comment by eguane** [comment]
> > Hi, did you expect to backport it to v12 ?
> > between 80% and 90% of company in belgium using cash discount with this scenario: deducted discount from amount total without reducing VAT base, is it possible with your module.
> > Rgds
> 
> Not at the moment, but I think it shouldn't be so hard to migrate this from 10.0 to 12.0

Thank for your feedback, I tested V13 module, I probably miss something into the configuration. Company discount and payment term are both configured. When I try to add payment from the invoice, The amount proposed is always the invoice one, not discounted.  Also if not already embeded, is it envisageable to add the value of the discount into a comment on the invoice, like "cash discount of xxx€ if paid before end date xx/xx/xx" 
Can you confirm that the scenario deducted discount from amount total without reducing VAT base, is it possible with your module?
Rgds

**Comment by sbidoul** [comment]
cross referencing account_financial_discount that covers a similar scope: https://github.com/OCA/account-financial-tools/pull/1040

**Comment by sanrav** [comment]
functional testing OK

**Comment by acsonefho** [comment]
@sbidoul @adrienpeiffer Is it possible to review and merge this PR please? Thanks! (I see you in contributors)

**Comment by acsonefho** [comment]
@dreispt 
> /ocabot merge nobump

Can you review and merge please?

**Review by adrienpeiffer — APPROVED** [review]
LGTM

**Pull request merged**
