### PR TITLE
[14.0][MIG] account_payment_widget_amount

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
- Removed dependency on module account_move_line_auto_reconcile_hook
- Refactor Test for new structure on account.move, and account.payment
@ForgeFlow

### CODE REVIEW

**Comment by jcdrubay** [comment]
We are interested in this module (in v15).
Currently the runboat link does not work.
We will test this PR locally.

**Review by jcdrubay — APPROVED** [review]
Tested on local, it works as expected.

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Pull request merged**
