### PR TITLE
[13.0][MIG] account due list days overdue

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Migration to v.13

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
Hi @HaraldPanten ,
could you review please?

Thanks,

**Review by HaraldPanten — APPROVED** [review]
Tested on runbot. Functional review 👍

**Comment by HaraldPanten** [comment]
@MiquelRForgeFlow could you make a quick review, please? Thanks in advance!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
