### PR TITLE
Port module account_voucher_supplier_invoice_number to 8.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by joaoalf** [comment]
:+1: LGTM

**Comment by moylop260** [comment]
Could you remove the description key from manifest (Now, we have README file)?

``` bash
************* Module account_voucher_supplier_invoice_number.__openerp__
account_voucher_supplier_invoice_number/__openerp__.py:6: [C8103(manifest-deprecated-key), ] Deprecated key "description" in manifest file
```

https://travis-ci.org/OCA/account-payment/jobs/130029040#L433

**Comment by eLBati** [comment]
Comparing with 8.0 version, it seems `de.po` is missing, could you check?

Then, :+1: thanks

**Comment by ghost** [comment]
@eLBati @moylop260 Thanks for the review.
Added the missing po file and removed description key from manifest.

**Comment by moylop260** [comment]
Thanks
:+1:

**Pull request merged**
