### PR TITLE
[15.0][MIG] partner_aging

### PR DESCRIPTION
**Pull request by Urvisha-OSI**
Migrate Partner Aging by Date module from v14 to v15

### CODE REVIEW

**Comment by max3903** [comment]
@Urvisha-OSI please rename `partner_aging`

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI please rename `partner_aging`

@max3903 module is renamed as 'partner_aging'

**Review by max3903 — CHANGES_REQUESTED** [review]
@Urvisha-OSI Please fix CI issues

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Please fix CI issues

@max3903 CI issues are fixed please check it

**Comment by max3903** [comment]
@Urvisha-OSI Can you apply the fix from #553 ?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you apply the fix from #553 ?

@max3903 fixes are done from the #553, you can review it

**Comment by max3903** [comment]
@Urvisha-OSI #553 provides the fix on 14.0. The fix needs to be in 15.0 as well.

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI #553 provides the fix on 14.0. The fix needs to be in 15.0 as well.

@max3903 already done the fixes of #553 in this 15.0 PR

**Review by max3903 — APPROVED** [review]

**Pull request merged**
