### PR TITLE
[MIG] account_payment_return_import: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Account Payment Return Import
=============================

This module adds a generic wizard + methods to import payment return file
formats.

It's only the base to be extended by another modules.

Multiple payment return files contained in a zip are also supported.

**Migrated from:** https://github.com/OCA/account-payment/pull/116

**Depends on:**
- [x] account_payment_return: https://github.com/OCA/account-payment/pull/152

cc @Tecnativa

### CODE REVIEW

**Comment by chienandalu** [comment]
A basic csv parser has been added so better tests can be implemented and to have functionality on the module by itself.

**Comment by pedrobaeza** [comment]
@chienandalu rebase now that account_payment_return is merged. @luismontalba, please review after the rebase.

**Comment by chienandalu** [comment]
@pedrobaeza All green now

**Review by pedrobaeza — APPROVED** [review]
@luismontalba please review

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Pull request merged**
