### PR TITLE
[16.0][MIG] account_due_list_aging_comment: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
#546

### CODE REVIEW

**Review by Gelo-fl — APPROVED** [review]
Functional revision OK

**Comment by JavierIniesta** [comment]
Hi @RodrigoBM 
Please could you take into account this step from the migration wiki? (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)
- Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a procedure for reducing commits from "OCA Transbot...".

**Comment by RodrigoBM** [comment]
> Hi @RodrigoBM Please could you take into account this step from the migration wiki? (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)
> 
> * Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a procedure for reducing commits from "OCA Transbot...".

Done

**Review by JavierIniesta — APPROVED** [review]
Code review: LGTM

**Comment by RodrigoBM** [comment]
can @bizzappdev review it?

**Review by SirAionTech — APPROVED** [review]
Thanks for the PR!
I have only done a code review and checked the commit history, looks good to me

**Comment by RodrigoBM** [comment]
add rebase 16.0

**Comment by SirAionTech** [comment]
@OCA/banking-maintainers this has 3 reviews and is https://github.com/OCA/account-payment/labels/ready%20to%20merge, can someone please merge? Thanks!

**Comment by RodrigoBM** [comment]
@pedrobaeza can you merge it?

**Comment by pedrobaeza** [comment]
Merging based on existing reviews:

/ocabot merge nobump
/ocabot migration account_due_list_aging_comment

**Comment by RodrigoBM** [comment]
> Merging based on existing reviews:
> 
> /ocabot merge nobump /ocabot migration account_due_list_aging_comment

Thanks @pedrobaeza

**Pull request merged**
