### PR TITLE
[12.0][WIP]: Import payment return file with multiple xml documents

### PR DESCRIPTION
**Pull request by sbejaoui**
Known issue in BNP France payment return files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But is it allowed to return several payment returns?

**Comment by sbejaoui** [comment]
@pedrobaeza , I don't get your question?

**Comment by pedrobaeza** [comment]
Before this PR, a single payment return was returned. Now it's a list. Is that properly handled by `account_payment_return_import`?

**Comment by sbejaoui** [comment]
The pain and camt parser return already a list of payment return.
https://github.com/OCA/account-payment/blob/883839a6969a246df21a7da7730459e60fdf029b/account_payment_return_import_iso20022/wizard/camt_parser.py#L140-L158

**Comment by pedrobaeza** [comment]
OK, great. It was just for being sure.

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by ThomasBinsfeld** [comment]
@sbejaoui Could you replace the "WIP" in the title by a "IMP"?

**Review by chrisdec — APPROVED** [review]
Functional test

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
