### PR TITLE
[12.0][FIX] account_payment_term_partner_holiday: Prevent error in tests when sale addon installed

### PR DESCRIPTION
**Pull request by victoralmau**
Prevent error in tests when sale addon installed.

Steps to reproduce:
- Install `account_payment_term_partner_holiday`
- Install `sale`
- Run `account_payment_term_partner_holiday` tests

Please @joao-p-marques and @pedrobaeza can you review it?

@Tecnativa TT30526

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not the solution at all, as this is only postponing other kind of problems. Please start putting which is the error in integration environments, and then we can see options.

**Comment by victoralmau** [comment]
> This is not the solution at all, as this is only postponing other kind of problems. Please start putting which is the error in integration environments, and then we can see options.

Description explain now steps to reproduce error in tests.

**Comment by pedrobaeza** [comment]
I still don't see the error given in tests.

**Comment by victoralmau** [comment]
Sorry, after careful review it seems that no change is necessary.

**Pull request closed without merging**
