### PR TITLE
[FIX] account_payment_term_discount: payment_state in tests

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by RLeeGML — APPROVED** [review]

**Comment by RLeeGML** [comment]
LGTM

**Comment by RLeeGML** [comment]
While running pre-commit
fatal: unable to access 'https://gitlab.com/PyCQA/flake8/': The requested URL returned error: 503

Gitlab is experiencing service issues
https://status.gitlab.com/

**Comment by max3903** [comment]
/ocabot merge patch

> Web traffic should be returning back to normal.

**Pull request merged**
