### PR TITLE
[16.0][ADD] New module : Account due list invoice link

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module creates a button on the invoice to view the payments and due dates related to that invoice.

payment_and_due_list

### CODE REVIEW

**Review by dacrumau — APPROVED** [review]
Probado y funciona perfectamente

**Comment by dacrumau** [comment]
Probado y funciona perfectamente.

**Comment by dani-xtendoo** [comment]
Funcionando correctamente

**Review by dani-xtendoo — APPROVED** [review]
Funciona perfectamente

**Pull request closed without merging**
