### PR TITLE
[15.0][MIG] account_payment_return_import: Migration to 15.0

### PR DESCRIPTION
**Pull request by LudLaf**
Standard migration to 15.0

@Tecnativa TT36430

@ernestotejeda and @pedrobaeza please review.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@LudLaf can you review the pre-commit and test failures?

**Comment by LudLaf** [comment]
> review

@carlosdauden  please check this out.

**Comment by japarici** [comment]
@LudLaf, @carlosdauden could you review failures, please?

**Review by ao-landoo — APPROVED** [review]
pre-commit failing. Otherwise looks good.

**Comment by carlosdauden** [comment]
pre-commit fixed

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
