### PR TITLE
[DRAFT][FIX][14.0] account_payment_term_discount (Issue 414)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Fix for Issue #414

### CODE REVIEW

**Comment by patrickrwilson** [comment]
This PR is a work in progress as there is testing and possible changes still.

@dreispt Here is the start of the fix that I could use your assistance testing. It now should work for both a single invoice payment as well as grouped batch payments. It does NOT apply the discounts if the user does a batch payment without grouping and will process normally in that case.

Is this something we should look at adding or leave it to just work in single or grouped payments?

**Comment by patrickrwilson** [comment]
This will need more design work before completing but will keep here for reference until then.

**Comment by dreispt** [comment]
This is probably related to #398?

**Comment by patrickrwilson** [comment]
> This is probably related to #398?

Looks like it, so perhaps this pr isn't needed anymore.

**Comment by patrickrwilson** [comment]
Closing this as there is currently work being done on batch processing and another module connecting them. See issue #398

**Pull request closed without merging**
