### PR TITLE
[15.0][MIG] account_payment_return: Migration to 15.0

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa TT36429

### CODE REVIEW

**Review by rp-landoo — APPROVED** [review]
Functional approval

**Comment by ao-landoo** [comment]
Did you remove `return_auto_reconcile` field for a reason?

**Comment by carlosdauden** [comment]
What exactly does this field provide in v15?

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
