### PR TITLE
16.0 mig account payment batch process

### PR DESCRIPTION
**Pull request by noharr**

### CODE REVIEW

**Comment by isabellerichard** [comment]
Hi @pedrobaeza , I would like to understand why @noharr 's PR is rejected about code coverage, whereas the version 15.0 of this module were merged without any tests here: https://github.com/OCA/account-payment/pull/539

We will try to add some tests to increase coverage but was there a special treatment about version 15.0?

Thanks for your help!

**Comment by pedrobaeza** [comment]
It's not rejected. It's simply that the code coverage has lowered applying with this PR. It's a quality metric, but it's not enforced for merging modules. The other metrics should be green though. Check https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_development_status.rst for information about the requirements.

**Comment by metaminux** [comment]
Hi everyone,

#564 is already approved for migrating account_payment_batch_process and none of them are listed in #546 

Can someone with sufficient rights helps to mutualize the efforts ?

**Comment by StefanRijnhart** [comment]
I'm rather troubled that we have a payment related module in the OCA without any unit test. #564 has a serious issue that would not have gone unnoticed otherwise. Would you consider to add the tests in this PR?

**Review by robinkeunen — COMMENTED** [review]
The pr looks good but tests would be nice indeed.

**Comment by robinkeunen** [comment]
Hey there, I added a test over in https://github.com/OCA/account-payment/pull/716 to move this forward.

**Comment by JordiBForgeFlow** [comment]
Superseded by https://github.com/OCA/account-payment/pull/716

**Pull request closed without merging**
