### PR TITLE
[11.0][MIG] account_due_list_aging_comments

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Without plurals, please :wink: Isn't better to use `account_credit_control` for this?

**Comment by MiquelRForgeFlow** [comment]
I don't know much about the `account_credit_control` module, but I see that has many features, that maybe the people that use the `account_due_list_aging_comment` module don't want.

**Comment by pedrobaeza** [comment]
Well, you are having a lot of modules for credit control (this one, the aging days, and so on), that are treated in a more flow oriented way in that module, so it deserves you to check it (tell me if you need a quick tour) and maybe replace them.

**Comment by MiquelRForgeFlow** [comment]
Well, the quick tour would be really nice 😊

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Quick merge. This is a trivial migration.

**Pull request merged**
