### PR TITLE
14.0 mig account payment return import

### PR DESCRIPTION
**Pull request by pablo-lp**

### CODE REVIEW

**Comment by jcbr87** [comment]
Hello @pablo-lp, I have tried this migration and it is fine.
I just think you will need to clear your commit history to get it shuffled.

**Comment by jaiodoo** [comment]
Hello @pablo-lp , being interested in the migration of this module, I have reviewed this branch and it seems to me that it works correctly.

**Review by mariadforgeflow — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
@pablo-lp could you fix the conflicst in this pr?

**Comment by LoisRForgeFlow** [comment]
This module is already merged https://github.com/OCA/account-payment/tree/14.0/account_payment_return_import. This PR can be closed.

**Pull request closed without merging**
