### PR TITLE
[16.0][FIX] account_payment_return: Add 'is_exchange' value to dict returned in prepare_values_returned_widget method

### PR DESCRIPTION
**Pull request by sergiobstoj**
**Current behaviour:**

- When having an invoice with returns, there is an error when printing PDF:

[Grabación de pantalla desde 29-10-24 12:26:33.webm](https://github.com/user-attachments/assets/9e346ce8-75f0-4c53-a742-09f42f1dea28)

**Behaviour with this PR:**

- The PDF is generated corrrectly.

[Grabación de pantalla desde 29-10-24 12:29:16.webm](https://github.com/user-attachments/assets/e2753540-c372-4ddd-abcd-2be2e2443094)

### CODE REVIEW

**Review by ljsalvatierra-factorlibre — APPROVED** [review]

**Review by PabloMartFL — APPROVED** [review]
Functional Review ok!

Whenever you try to print any invoice linked to a payment return, the invoice is printed correctly 
https://www.awesomescreenshot.com/video/33069145?key=0ac0e955912d12b3eb4fef069a9c5595

**Comment by sergiobstoj** [comment]
@pedrobaeza is OK for merge?

**Review by pedrobaeza — COMMENTED** [review]
Thanks for the patch.

Why don't always putting `is_exchange = False`? Returned elements are not going to be exchange moves for sure.

**Comment by sergiobstoj** [comment]
@pedrobaeza Suggestion applied. Ok for merge?

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
I'm now remembering this refactor that phases out this change: https://github.com/OCA/account-payment/pull/778

**Pull request merged**
